version: 2.1
jobs:
  build:
    docker:
      - image: tsguna007/jp-512-nx:latest
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          command: |
            echo "Running makefile"
            make build
      - run:
          command: |
            ./test
